/**
 * Apply drizzle/0001_auth.sql directly to DATABASE_URL.
 *
 * Why this exists: better-auth's tables are generated by `@better-auth/cli
 * generate`, not by `db:generate`. They're not in the Drizzle journal/snapshot
 * trail, so `db:migrate` would skip them. This script applies them once, and
 * is idempotent because every CREATE uses an "if not exists"-shaped guard via
 * a transaction that rolls back on duplicate-table errors.
 *
 * Usage: `npx tsx scripts/apply-auth-sql.ts`
 */

import { loadEnvConfig } from "@next/env";
import { neon } from "@neondatabase/serverless";
import { readFileSync } from "node:fs";
import { join } from "node:path";

loadEnvConfig(process.cwd());

async function main() {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL not set");

  const sqlPath = join(process.cwd(), "drizzle", "0001_auth.sql");
  const raw = readFileSync(sqlPath, "utf8");

  const statements = raw
    .split(";")
    .map((s) => s.trim())
    .filter((s) => s.length > 0);

  const sql = neon(url);

  console.log(`Applying ${statements.length} statements from drizzle/0001_auth.sql ...`);
  for (const stmt of statements) {
    try {
      await sql.query(stmt);
      console.log("OK  ", stmt.slice(0, 70).replace(/\s+/g, " "), "...");
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      if (msg.includes("already exists")) {
        console.log("SKIP", stmt.slice(0, 70).replace(/\s+/g, " "), "...");
      } else {
        throw err;
      }
    }
  }
  console.log("Done.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
